[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{project_name}}"
description = "{{project_description}}"
version = "0.1.0"
authors = [{ name = "{{author_name}}" }]
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "qiskit",
    "qutip",
    "weylchamber",
    "matplotlib",
    "LovelyPlots",
]

[project.optional-dependencies]
dev = ["ipykernel", "pre-commit", "pylatexenc"]
format = [
    "pre-commit",
    "black[jupyter]",
    "isort",
    "tomli",
    "pydocstyle",
    "ruff",
    "docformatter[tomli]",
]
test = ["pytest"]

[tool.ruff]
target-version = "py39"
fix = true

[tool.isort]
profile = "black"
