[project]
name = "my_package"
description = "My package description"
version = "0.1.0"
authors = [
    { name = "Evan McKinney", email = "evmckinney9@gmail.com" }
]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel"]
