[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "_lib"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.15", features = ["extension-module"] }
num-complex = "0.4"
ndarray = "0.15.3"
numpy = "0.15"
