name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pre-commit packages
        run: pip install .[format]
      - name: Run pre-commit
        run: pre-commit run --all-files
