name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    if: github.repository != 'evmckinney9/python-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if template_flag.yml exists
        if: ${{ hashFiles('.github/template_flag.yml') != '' }}
        run: |
          echo "template_flag.yml exists. Exiting early."
          exit 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip'
          cache-dependency-path: "**/pyproject.toml"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test] --quiet
      - name: Run pytest
        run: pytest src/tests/
